### PR TITLE
Fixed apples spawning on top of the snake

### PR DESCRIPTION
**Pull request by pedrohdjs**
Fixes issue #4, where apples could spawn somewhere on the snake's body.

This was fixed by checking if the position where the apple spawned matches the position of any piece of the snake's body (head or tail segment) in the apple's constructor. If it happens, a new random position is chosen for the apple until it no longer is spawned in the snake's body.

To validate if this works, you may add some print statements to the while loop on line 207. This becomes more and more frequent as the snake grows larger.

### CODE REVIEW

**Review by lincolncpp — APPROVED** [review]
it looks good to me!

**Review by lincolncpp — CHANGES_REQUESTED** [review]
it looks good to me. Can you please point it to `dev` branch instead?

**Comment by pedrohdjs** [comment]
Thanks @lincolncpp ! When I first got here, it was tudo mato, so we didn't have a dev branch back then. I just pointed the PR to the right branch, thanks for reviewing!

**Review by JoaoVictorDBP — APPROVED** [review]
It appears to be working correctly.

**Comment by roselino-quatro** [comment]
sorry, was not paying attention and solved a conflict on the wrong PR

**Comment by ImLusca** [comment]
Works fine. Just need a rebase to fix the conflicts

**Review by ImLusca — APPROVED** [review]

**Comment by pedrohdjs** [comment]
@lincolncpp Since I pointed it at the right branch and rebased (actually, merged) this, I'll be merging without waiting for the requirements

**Pull request merged**
