### PR TITLE
bug/120/speed reset: fixed both speed not resetting and correctly placed musics/ and assets/ directories.

### PR DESCRIPTION
**Pull request by rodrigo-lex**
Title

### CODE REVIEW

**Review by Petroncini — COMMENTED** [review]
Bug fix looks good, the file structure is outdated though

**Review by lucasclaros — APPROVED** [review]
I think with the conflicts resolved you're good to go and merge! The bug seems to be fixed!

**Review by laurafcamargos — APPROVED** [review]
Just resolve the conflicts!

**Review by laurafcamargos — COMMENTED** [review]
I believe PR #168 has already resolved this.

**Pull request closed without merging**
