### PR TITLE
Bug/189/grid resize

### PR DESCRIPTION
**Pull request by raultel**
Solving #189

### CODE REVIEW

**Review by rodrigo-lex — CHANGES_REQUESTED** [review]
works great for both small and medium size grids, and pretty fine for the big size - however there is one remaining bug: the snake can die not only from touching the obstacle, but also from crossing the square to the left of the obstacle:

image

image

above are two examples of this happening.

**Comment by raultel** [comment]
> works great for both small and medium size grids, and pretty fine for the big size - however there is one remaining bug: the snake can die not only from touching the obstacle, but also from crossing the square to the left of the obstacle:
> 
> image
> 
> image
> 
> above are two examples of this happening.

This doesn't appear to be a new bug, just tested this and the current branch (v1.0.0) and it already has this bug.
Should we make a new issue and pr to solve it?

**Comment by raultel** [comment]
Just deleted my previous comment because on my tests i thought to replicate this on the main branch.
It appears I had died of energy lol. The bug really is new.
Working on it!

**Comment by raultel** [comment]
Should be working now!
Thanks for pointing out the bug

**Comment by rodrigo-lex** [comment]
yep, seems fine now!

**Pull request merged**
