### PR TITLE
feat: add a menu screen which shows avaiable options and let's the user select them (#43)

### PR DESCRIPTION
**Pull request by raultel**
Opens/closes with 'the o' key
Only the screen was implemented, it is yet not possible to change the options. 
The key press isn't registering properly, sometimes you have to press the key 2 times to close it.

### CODE REVIEW

**Comment by roselino-quatro** [comment]
Theres already a very similar feature merged in dev by #25, also I was not able to open the menu

**Comment by roselino-quatro** [comment]
> also I was not able to open the menu

its supposed to only work mid game or is it a bug?

**Comment by liestrela** [comment]
Menu works partially here. I'm working in some improvements (modularizing and fixing event loop issues) and I think we are good to go.

**Comment by raultel** [comment]
> > also I was not able to open the menu
> 
> its supposed to only work mid game or is it a bug?

I made it to work only mid game, but looking back it should also be part of the main menu

**Comment by raultel** [comment]
> Theres already a very similar feature merged in dev by #25, also I was not able to open the menu

We should maybe combine both menus, I'll be waiting for li's improvements then try to combine then if necessary, since this merge will permit more generic options and scalability

**Pull request closed without merging**
